---
title: "Relationship Between Upper Respiratory Tract Infection in Pregnancy and Adverse Birth Outcomes"
subtitle: "BMIN503/EPID600 Final Project"
author: "Sarah Rothbard"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required. I added a new sentence

## Overview {#sec-overview}

Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

For my final project, it is my goal to understand the relationship between pre-conception iron biomarkers and miscarriage risk. Specifically, I will be investigating this question among women with prior pregnancy loss, using data from the EAGeR (Effects of Aspirin in Gestation and Reproduction) trial.

Two faculty members I met with to discuss this project: 
Sunni Mumford, Professor & Deputy Director, Epidemiology Ellen Caniglia, Assistant Professor, Epidemiology

Sunni Mumford has worked with EAGeR data before and informed me about the EAGeR data structure and best practices for the analyses. We discussed the feasibility of my research question; data is available within EAGeR on both iron biomarkers and miscarriage. Iron biomarker data is from baseline (preconception) and pregnancy loss data is collected during follow-up with the time metric being menstrual cycle (up to 6 cycles). Ellen Caniglia encouraged me to perform a literature review to determine which iron biomarker may be best to use and after discussion, we decided on serum ferritin. With both Dr. Mumford and Dr. Caniglia, I discussed potential confounders based on the literature.

[srothbard](https://github.com/srothbard/BMIN503_Final_Project)

## Introduction {#sec-introduction}

Describe the problem addressed, its significance, and some background to motivate the problem. This should extend what is in the @sec-overview.

Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
